[2024-05-25T16:37:22.508+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T16:37:22.522+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_minio_s3_v01.upload_file_to_minio manual__2024-05-25T16:37:21.483926+00:00 [queued]>
[2024-05-25T16:37:22.529+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_minio_s3_v01.upload_file_to_minio manual__2024-05-25T16:37:21.483926+00:00 [queued]>
[2024-05-25T16:37:22.529+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-25T16:37:22.542+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_file_to_minio> on 2024-05-25 16:37:21.483926+00:00
[2024-05-25T16:37:22.574+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=452) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-25T16:37:22.576+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_minio_s3_v01', 'upload_file_to_minio', 'manual__2024-05-25T16:37:21.483926+00:00', '--job-id', '177', '--raw', '--subdir', 'DAGS_FOLDER/csv_copy_to_mino_dag.py', '--cfg-path', '/tmp/tmp05ar7uzv']
[2024-05-25T16:37:22.577+0000] {standard_task_runner.py:63} INFO - Started process 453 to run task
[2024-05-25T16:37:22.577+0000] {standard_task_runner.py:91} INFO - Job 177: Subtask upload_file_to_minio
[2024-05-25T16:37:22.615+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_minio_s3_v01.upload_file_to_minio manual__2024-05-25T16:37:21.483926+00:00 [running]> on host fd6401a86447
[2024-05-25T16:37:22.683+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_minio_s3_v01' AIRFLOW_CTX_TASK_ID='upload_file_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T16:37:21.483926+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-25T16:37:21.483926+00:00'
[2024-05-25T16:37:22.684+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T16:37:22.701+0000] {base.py:84} INFO - Using connection ID 'minio_s3' for task execution.
[2024-05-25T16:37:22.702+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from extra.
[2024-05-25T16:37:23.025+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-25T16:37:23.026+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T16:37:23.034+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_minio_s3_v01, task_id=upload_file_to_minio, run_id=manual__2024-05-25T16:37:21.483926+00:00, execution_date=20240525T163721, start_date=20240525T163722, end_date=20240525T163723
[2024-05-25T16:37:23.072+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-25T16:37:23.085+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-25T16:37:23.089+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
