[2024-05-23T15:44:13.511+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-23T15:44:13.534+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_copy_dag.copy_csv scheduled__2024-05-22T00:00:00+00:00 [queued]>
[2024-05-23T15:44:13.540+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_copy_dag.copy_csv scheduled__2024-05-22T00:00:00+00:00 [queued]>
[2024-05-23T15:44:13.541+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-23T15:44:13.551+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): copy_csv> on 2024-05-22 00:00:00+00:00
[2024-05-23T15:44:13.561+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_copy_dag', 'copy_csv', 'scheduled__2024-05-22T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/csv_copy_dag.py', '--cfg-path', '/tmp/tmplwmxhil_']
[2024-05-23T15:44:13.561+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=243) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-23T15:44:13.562+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask copy_csv
[2024-05-23T15:44:13.562+0000] {standard_task_runner.py:63} INFO - Started process 244 to run task
[2024-05-23T15:44:13.602+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_copy_dag.copy_csv scheduled__2024-05-22T00:00:00+00:00 [running]> on host 499c55d2c0c9
[2024-05-23T15:44:13.675+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_copy_dag' AIRFLOW_CTX_TASK_ID='copy_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-05-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-22T00:00:00+00:00'
[2024-05-23T15:44:13.676+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-23T15:44:13.698+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-23T15:44:13.698+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/csv_copy_dag.py", line 30, in copy_csv_file
    shutil.copy(src, dest)
  File "/usr/local/lib/python3.12/shutil.py", line 435, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.12/shutil.py", line 260, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/source/sample.csv'
[2024-05-23T15:44:13.707+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_copy_dag, task_id=copy_csv, run_id=scheduled__2024-05-22T00:00:00+00:00, execution_date=20240522T000000, start_date=20240523T154413, end_date=20240523T154413
[2024-05-23T15:44:13.717+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task copy_csv ([Errno 2] No such file or directory: '/opt/airflow/data/source/sample.csv'; 244)
[2024-05-23T15:44:13.737+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-23T15:44:13.750+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-23T15:44:13.752+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-23T16:07:46.216+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-23T16:07:46.237+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_copy_dag.copy_csv scheduled__2024-05-22T00:00:00+00:00 [queued]>
[2024-05-23T16:07:46.246+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_copy_dag.copy_csv scheduled__2024-05-22T00:00:00+00:00 [queued]>
[2024-05-23T16:07:46.247+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-23T16:07:46.261+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): copy_csv> on 2024-05-22 00:00:00+00:00
[2024-05-23T16:07:46.266+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=90) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-23T16:07:46.268+0000] {standard_task_runner.py:63} INFO - Started process 91 to run task
[2024-05-23T16:07:46.267+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_copy_dag', 'copy_csv', 'scheduled__2024-05-22T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/csv_copy_dag.py', '--cfg-path', '/tmp/tmp__mhqort']
[2024-05-23T16:07:46.269+0000] {standard_task_runner.py:91} INFO - Job 39: Subtask copy_csv
[2024-05-23T16:07:46.311+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_copy_dag.copy_csv scheduled__2024-05-22T00:00:00+00:00 [running]> on host e6328d9852f4
[2024-05-23T16:07:46.380+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_copy_dag' AIRFLOW_CTX_TASK_ID='copy_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-05-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-22T00:00:00+00:00'
[2024-05-23T16:07:46.381+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-23T16:07:46.405+0000] {logging_mixin.py:188} INFO - Copied /opt/***/dags/source/sample.csv to /opt/***/dags/destination/sample.csv
[2024-05-23T16:07:46.405+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-23T16:07:46.407+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-23T16:07:46.415+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=csv_copy_dag, task_id=copy_csv, run_id=scheduled__2024-05-22T00:00:00+00:00, execution_date=20240522T000000, start_date=20240523T160746, end_date=20240523T160746
[2024-05-23T16:07:46.442+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-23T16:07:46.457+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-23T16:07:46.459+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
