[2024-05-25T16:37:02.571+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T16:37:02.586+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_123.upload_file_to_minio manual__2024-05-25T16:37:01.225953+00:00 [queued]>
[2024-05-25T16:37:02.593+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_123.upload_file_to_minio manual__2024-05-25T16:37:01.225953+00:00 [queued]>
[2024-05-25T16:37:02.593+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-25T16:37:02.606+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_file_to_minio> on 2024-05-25 16:37:01.225953+00:00
[2024-05-25T16:37:02.612+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=448) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-25T16:37:02.614+0000] {standard_task_runner.py:63} INFO - Started process 449 to run task
[2024-05-25T16:37:02.614+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_123', 'upload_file_to_minio', 'manual__2024-05-25T16:37:01.225953+00:00', '--job-id', '176', '--raw', '--subdir', 'DAGS_FOLDER/test_123.py', '--cfg-path', '/tmp/tmpthldwt4z']
[2024-05-25T16:37:02.615+0000] {standard_task_runner.py:91} INFO - Job 176: Subtask upload_file_to_minio
[2024-05-25T16:37:02.652+0000] {task_command.py:426} INFO - Running <TaskInstance: test_123.upload_file_to_minio manual__2024-05-25T16:37:01.225953+00:00 [running]> on host fd6401a86447
[2024-05-25T16:37:02.719+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_123' AIRFLOW_CTX_TASK_ID='upload_file_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T16:37:01.225953+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-25T16:37:01.225953+00:00'
[2024-05-25T16:37:02.720+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T16:37:02.736+0000] {base.py:84} INFO - Using connection ID 'minio_s3' for task execution.
[2024-05-25T16:37:02.737+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from extra.
[2024-05-25T16:37:03.007+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-25T16:37:03.008+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T16:37:03.015+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=test_123, task_id=upload_file_to_minio, run_id=manual__2024-05-25T16:37:01.225953+00:00, execution_date=20240525T163701, start_date=20240525T163702, end_date=20240525T163703
[2024-05-25T16:37:03.069+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-25T16:37:03.082+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-25T16:37:03.084+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
